### ISSUE TITLE
Help has extra newline in Windows 7

### ISSUE THREAD

**Issue by fireattack** [Last-Order/Erii#1]
Noticed this for quite a while in various tools created with Erii such as minyami and kkr.

Locale is Simp. Chinese if that matters.

![image](https://user-images.githubusercontent.com/4130991/86995330-5c75aa80-c16e-11ea-877e-179f763cf1ff.png)

![image](https://user-images.githubusercontent.com/4130991/86995376-78794c00-c16e-11ea-857a-421f9bea2ace.png)

![image](https://user-images.githubusercontent.com/4130991/86995478-c1c99b80-c16e-11ea-8577-46a48b5b3ec9.png)

**Comment by Last-Order** [comment]
Does this situation only happen on Windows7?

Since I don't have any Windows7 devices so I can't test it.

**Comment by fireattack** [comment]
It seems so. Cannot reproduce on my Win10 machine.

I will see if I can find the cause.

**Comment by fireattack** [comment]
研究了下 好像是win 7的一个bug（？）

如果输出长度等于column数目的话，会莫名换行
比如以下代码：
```js
console.log('-------------------------------start-------------------------------');
var col = process.stdout.columns;
console.log("a".repeat(col))
console.log('--------------------------------end--------------------------------');
```
第二行会换行 `console.log("a".repeat(col-1))`就不会了。

对于`Erii`的话，把`.fill()`去掉就可以
不过不是很重要 所以改不改都行…

**Comment by Last-Order** [comment]
要不你直接来个PR吧，不然就别改了（
